# Numpy

- Create Arrays and Grids
    - One dimension array
    - Two dimension array
    - Zeros array
    - Ones array
    - X value array
    - Eye Matrix (identity matrix)
    - Create arrays using a range
    - Create array with linear interpolation
    - Create array with random numbers
- Get Attributes
    - Dimension of array
    - shape of array
    - Data type inside array
    - Size of the array
- shape manipulation
    -Re-shape
- Operations with Numpy
    - Sum, substract, divide, multiply
    - Sort
    - Concatenate
    - Sum, mean, min and max functions
    - Indexing and slicing
    - Copy
    - Save
    - Save as txt or csv
    - Load
    - Conditionals
    - Unique function
- Broadcasting 

In [8]:
import numpy as np

In [30]:
print(help(np.array),help(np.zeros))

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

### Create Arrays and Grids

----- One and two dimension arrays -----

In [33]:
a1 = np.array(list(range(0,10)))
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
a2 = np.array([list(range(0,4)),list(range(10,14))])
a2

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

----- Zero, Ones, Random and X arrays -----

In [40]:
zero_array = np.zeros(shape=(3,3))
zero_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
ones_array = np.ones(shape=(3,6))
ones_array

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [49]:
x_array = np.full((2,3),fill_value=7)
x_array

array([[7, 7, 7],
       [7, 7, 7]])

----- Eye Matrix -----

In [51]:
eye = np.eye(5)
eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

----- Create Array using range -----

In [64]:
rangearray = np.arange(0,20,step=2)
rangearray

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

----- Array with linear interpolation -----

In [66]:
linear_array = np.linspace(10,20,num=5)
linear_array

array([10. , 12.5, 15. , 17.5, 20. ])

----- Random numbers arrays -----

In [58]:
ran_array = np.random.random(size=(2,3)) #Returns random numbers from 0 to 1
ran_array

array([[0.29615493, 0.64210837, 0.00433338],
       [0.82620329, 0.23832451, 0.30835424]])

In [59]:
ran_array2 = np.random.randint(10,20,size=(4,4))
ran_array2

array([[18, 12, 15, 16],
       [10, 17, 11, 17],
       [15, 12, 16, 14],
       [10, 14, 19, 10]])

# Get Attributes

In [68]:
ran_array2.ndim

2

In [69]:
ran_array2.shape

(4, 4)

In [70]:
ran_array2.dtype

dtype('int32')

In [71]:
ran_array2.size

16

# Shape Manipulation

In [81]:
ran_array2.reshape(8,2) #reshape must be compatible (rows and columns relationship)

array([[18, 12],
       [15, 16],
       [10, 17],
       [11, 17],
       [15, 12],
       [16, 14],
       [10, 14],
       [19, 10]])

In [83]:
#use -1 to auto shape the row or column:
ran_array2.reshape(2,-1)

array([[18, 12, 15, 16, 10, 17, 11, 17],
       [15, 12, 16, 14, 10, 14, 19, 10]])

# Numpy Operations

In [84]:
eye2 = eye + eye
eye2

array([[2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 2., 0., 0.],
       [0., 0., 0., 2., 0.],
       [0., 0., 0., 0., 2.]])

In [93]:
ran_array2.sort(axis=0)
ran_array2

array([[10, 10, 11, 12],
       [10, 12, 14, 15],
       [14, 15, 16, 16],
       [17, 17, 18, 19]])

In [96]:
print(
f'Sum: {ran_array2.sum()}\nMin: {ran_array2.min()}\nMax: {ran_array2.max()}\nMean: {ran_array2.mean()}'
)

Sum: 226
Min: 10
Max: 19
Mean: 14.125


----- Indexing and Slicing -----

----- Copy, save and load -----

In [98]:
clone = ran_array2.copy()
clone

array([[10, 10, 11, 12],
       [10, 12, 14, 15],
       [14, 15, 16, 16],
       [17, 17, 18, 19]])

In [99]:
np.save('clone.npy',clone)

In [102]:
np.savetxt('np.csv',clone,fmt='%.2f',delimiter=',')

In [104]:
load = np.load('clone.npy')
load

array([[10, 10, 11, 12],
       [10, 12, 14, 15],
       [14, 15, 16, 16],
       [17, 17, 18, 19]])

In [105]:
loadcsv = np.loadtxt('np.csv',delimiter=',')
loadcsv

array([[10., 10., 11., 12.],
       [10., 12., 14., 15.],
       [14., 15., 16., 16.],
       [17., 17., 18., 19.]])

----- Conditionals -----