# 9. Pytorch Fundamentals

- **Reference information**
- **Create Tensors**
    - torch.randint
    - torch.arange
    - torch.arange with trick to make them float
    - torch rand (return scalars between 0 and 1)
    - torch.randn (return scalars from the standard normal dist)
    - torch.linspace
    - torch.empty
    - torch.zeros
    - torch.zeros_like (Returns tensor filled with 0s with the same size as input.
    - torch.ones
    - torch.ones_like
    - torch.full
- **Convert to Tensors**
    - from_numpy
    - as_tensor
    - tensor and Tensor (One converts to int and the other float)
    - FloatTensor
- **Handle Tensor Dimensions**
    - reshape (this function will copy the underlying data)
    - view   (this function will not copy the underlying data)
    - view_as
    - unsqueeze
    - Use of None expression
    - Slice Notation for Even Numbers
    - Slice Notation for Odd Numbers
    - Handle Tensor Ops based on dimensions
- **Tensor Operations**
    - Change Tensor type
    - torch.cat
    - torch.stack
    - Matrix Transpose
    - Permute
    - torch.where
    - Slice Notation
    - Math Ops
- **Tensor Attributes**
    - Shape or Size (same thing)
    - Device (CPU or GPU)
    - Layout
    - Mean
    - Max
    - argmin, argmax
    - sum
    - unique
- **Probability Dist Functions**

In [3]:
import torch
import torch.distributions as dist
import numpy as np

## Reference information

<h2><a href='https://pytorch.org/docs/stable/tensors.html'>Tensor Datatypes</a></h2>
<table style="display: inline-block">
<tr><th>TYPE</th><th>NAME</th><th>EQUIVALENT</th><th>TENSOR TYPE</th></tr>
<tr><td>32-bit integer (signed)</td><td>torch.int32</td><td>torch.int</td><td>IntTensor</td></tr>
<tr><td>64-bit integer (signed)</td><td>torch.int64</td><td>torch.long</td><td>LongTensor</td></tr>
<tr><td>16-bit integer (signed)</td><td>torch.int16</td><td>torch.short</td><td>ShortTensor</td></tr>
<tr><td>32-bit floating point</td><td>torch.float32</td><td>torch.float</td><td>FloatTensor</td></tr>
<tr><td>64-bit floating point</td><td>torch.float64</td><td>torch.double</td><td>DoubleTensor</td></tr>
<tr><td>16-bit floating point</td><td>torch.float16</td><td>torch.half</td><td>HalfTensor</td></tr>
<tr><td>8-bit integer (signed)</td><td>torch.int8</td><td></td><td>CharTensor</td></tr>
<tr><td>8-bit integer (unsigned)</td><td>torch.uint8</td><td></td><td>ByteTensor</td></tr></table>

**Tensor Operations**


A <a href='https://en.wikipedia.org/wiki/Dot_product'>dot product</a> is the sum of the products of the corresponding entries of two 1D tensors. If the tensors are both vectors, the dot product is given as:<br>

$\begin{bmatrix} a & b & c \end{bmatrix} \;\cdot\; \begin{bmatrix} d & e & f \end{bmatrix} = ad + be + cf$

If the tensors include a column vector, then the dot product is the sum of the result of the multiplied matrices. For example:<br>
$\begin{bmatrix} a & b & c \end{bmatrix} \;\cdot\; \begin{bmatrix} d \\ e \\ f \end{bmatrix} = ad + be + cf$<br><br>
Dot products can be expressed as <a href='https://pytorch.org/docs/stable/torch.html#torch.dot'><strong><tt>torch.dot(a,b)</tt></strong></a> or `a.dot(b)` or `b.dot(a)`

## Create Tensors


    - torch.randint
    - torch.arange
    - torch.arange with trick to make them float
    - torch rand (return scalars between 0 and 1)
    - torch.randn (return scalars from the standard normal dist)
    - torch.linspace
    - torch.empty
    - torch.zeros
    - torch.zeros_like (Returns tensor filled with 0s with the same size as input.
    - torch.ones
    - torch.ones_like

In [2]:
torch.randint(low=0,high=110,size=(3,3))

tensor([[ 76,  93,  91],
        [ 87,  22, 103],
        [ 98,  62,  57]])

In [3]:
torch.arange(start=0,end=110,step=10)

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [4]:
#with trick to make them float

torch.arange(start=0., end=110., step=10)

tensor([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [5]:
# return scalars between 0 and 1

torch.rand(size=(3,3))

tensor([[0.9903, 0.6571, 0.0703],
        [0.2785, 0.5521, 0.0156],
        [0.2837, 0.8880, 0.6073]])

In [6]:
# return scalars from the standard normal dist

torch.randn(size=(3,3))

tensor([[ 0.3971, -0.9261, -1.5116],
        [ 0.7428, -0.4200,  0.0467],
        [-1.1810, -0.1793,  0.7002]])

In [7]:
torch.linspace(start=0,end=100,steps=10)

tensor([  0.0000,  11.1111,  22.2222,  33.3333,  44.4444,  55.5556,  66.6667,
         77.7778,  88.8889, 100.0000])

In [8]:
torch.empty(size=(3,3))

tensor([[4.0891e+31, 7.8893e-43, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [9]:
torch.zeros(size=(3,3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [9]:
# Returns tensor filled with 0s with the same size as input.

x = torch.randint(low=0,high=110,size=(4,3)).float()

torch.zeros_like(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [11]:
torch.ones(size=(3,3))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [12]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [13]:
torch.full(size=(3,8),fill_value=32)

tensor([[32, 32, 32, 32, 32, 32, 32, 32],
        [32, 32, 32, 32, 32, 32, 32, 32],
        [32, 32, 32, 32, 32, 32, 32, 32]])

## Convert to Tensors

    - from_numpy
    - as_tensor
    - tensor and Tensor (one converts to int and the other float)
    - FloatTensor

In [14]:
xx = np.arange(0,110,10)
xx

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [15]:
torch.from_numpy(xx)

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100],
       dtype=torch.int32)

In [16]:
torch.as_tensor(xx)

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100],
       dtype=torch.int32)

In [17]:
#return tensor in integer data type

torch.tensor(xx)

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100],
       dtype=torch.int32)

In [18]:
# return tensor in float data type

torch.Tensor(xx)

tensor([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [19]:
torch.FloatTensor(xx)

tensor([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Handle tensor dimensions

    - reshape (this function will copy the underlying data)
    - view   (this function will not copy the underlying data)
    - view_as
    - unsqueeze
    - Use of None expression
    - Slice Notation for Even Numbers
    - Slice Notation for Odd Numbers
    - Handle Tensor Ops based on dimensions

In [20]:
x

tensor([[ 59, 102,  84],
        [ 78,   5,  41],
        [ 93,  63,  87],
        [ 50,  37,  10]])

In [21]:
x.reshape(2,2,-1)

tensor([[[ 59, 102,  84],
         [ 78,   5,  41]],

        [[ 93,  63,  87],
         [ 50,  37,  10]]])

In [22]:
x.view(3,-1)

tensor([[ 59, 102,  84,  78],
        [  5,  41,  93,  63],
        [ 87,  50,  37,  10]])

In [23]:
#Tensor will be seen with same dimension as another existing tensor

y = torch.randint(100,200,size=(4,3))

print(y,"\n\n" ,x.view_as(y))


tensor([[155, 174, 181],
        [120, 150, 125],
        [166, 106, 150],
        [114, 168, 143]]) 

 tensor([[ 59, 102,  84],
        [ 78,   5,  41],
        [ 93,  63,  87],
        [ 50,  37,  10]])


In [24]:
print(x.unsqueeze(dim=0), x.unsqueeze(dim=0).shape)
print('\n')
print(x.unsqueeze(dim=1),x.unsqueeze(dim=1).shape)
print('\n')
print(x.unsqueeze(dim=1),x.unsqueeze(dim=2).shape)

tensor([[[ 59, 102,  84],
         [ 78,   5,  41],
         [ 93,  63,  87],
         [ 50,  37,  10]]]) torch.Size([1, 4, 3])


tensor([[[ 59, 102,  84]],

        [[ 78,   5,  41]],

        [[ 93,  63,  87]],

        [[ 50,  37,  10]]]) torch.Size([4, 1, 3])


tensor([[[ 59, 102,  84]],

        [[ 78,   5,  41]],

        [[ 93,  63,  87]],

        [[ 50,  37,  10]]]) torch.Size([4, 3, 1])


In [25]:
print(f"""


{x.size()}

{x[:None].size()}

{x[None].size()}

{x[None,:].size()}

{x[None,:,None,:].size()}

{x[...,None,:,None].size()}

{x[None,None,:].size()}


""")




torch.Size([4, 3])

torch.Size([4, 3])

torch.Size([1, 4, 3])

torch.Size([1, 4, 3])

torch.Size([1, 4, 1, 3])

torch.Size([4, 1, 3, 1])

torch.Size([1, 1, 4, 3])





In [24]:
#Slice Notation for Even Numbers

torch.arange(0,110,10)[::2]

tensor([  0,  20,  40,  60,  80, 100])

In [26]:
#Slice Notation for Odd Numbers

torch.arange(0,110,10)[::3]

tensor([ 0, 30, 60, 90])

Handle Tensor ops based on dimensions

In [82]:
x = torch.arange(1,13,1).view(4,3).float()

2-D Tensor:

In [83]:
x

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [84]:
#Mean Along the Columns. Output Tensor will have 1 row but X columns

x.mean(dim=0,keepdim=True)

tensor([[5.5000, 6.5000, 7.5000]])

In [85]:
#Mean Along the ROWS. Output Tensor will have X rows and 1 row (2D)

x.mean(dim=1,keepdim=True)

tensor([[ 2.],
        [ 5.],
        [ 8.],
        [11.]])

3-D Tensor:

In [87]:
x = x.view(3,2,2)
x

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])

***With 3-Dimensions:***

Dimension 0: Across the 3 blocks:
- (1+5+9) /3 = 5
- (2+6+10) /3 = 6
- (3+7+11) /3 = 7
- (4+8+12) /3 = 8
               
Dimension 1:Along the columns in every block

Dimension 2: Along the rows in every block

In [89]:
#Dim 0
x.mean(dim=0)

tensor([[5., 6.],
        [7., 8.]])

In [90]:
#Dim 1
x.mean(dim=1)

tensor([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.]])

In [91]:
#Dim 2
x.mean(dim=2)

tensor([[ 1.5000,  3.5000],
        [ 5.5000,  7.5000],
        [ 9.5000, 11.5000]])

In [93]:
x.max(dim=0)

torch.return_types.max(
values=tensor([[ 9., 10.],
        [11., 12.]]),
indices=tensor([[2, 2],
        [2, 2]]))

## Tensor Operations

    - Change Tensor type
    - torch.cat
    - torch.stack
    - Matrix Transpose
    - Permute
    - torch.where
    - Slice Notation
    - Math Ops

In [26]:
torch.tensor(xx, dtype=torch.float64)

tensor([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.],
       dtype=torch.float64)

In [27]:
# Change dtypes and show x and y tensors
print(x.type(torch.float64),"\n\n", y.type(torch.float64))

tensor([[ 59., 102.,  84.],
        [ 78.,   5.,  41.],
        [ 93.,  63.,  87.],
        [ 50.,  37.,  10.]], dtype=torch.float64) 

 tensor([[155., 174., 181.],
        [120., 150., 125.],
        [166., 106., 150.],
        [114., 168., 143.]], dtype=torch.float64)


In [28]:
print(torch.cat([x,y],dim=0))
print('\n')
print(torch.cat([x,y],dim=1))

tensor([[ 59, 102,  84],
        [ 78,   5,  41],
        [ 93,  63,  87],
        [ 50,  37,  10],
        [155, 174, 181],
        [120, 150, 125],
        [166, 106, 150],
        [114, 168, 143]])


tensor([[ 59, 102,  84, 155, 174, 181],
        [ 78,   5,  41, 120, 150, 125],
        [ 93,  63,  87, 166, 106, 150],
        [ 50,  37,  10, 114, 168, 143]])


In [29]:
print(torch.stack([x,y],dim=0))
print('\n\n')
print(torch.stack([x,y],dim=1))

tensor([[[ 59, 102,  84],
         [ 78,   5,  41],
         [ 93,  63,  87],
         [ 50,  37,  10]],

        [[155, 174, 181],
         [120, 150, 125],
         [166, 106, 150],
         [114, 168, 143]]])



tensor([[[ 59, 102,  84],
         [155, 174, 181]],

        [[ 78,   5,  41],
         [120, 150, 125]],

        [[ 93,  63,  87],
         [166, 106, 150]],

        [[ 50,  37,  10],
         [114, 168, 143]]])


In [30]:
#Transpose
print(f'Tensor x:\n{x}\n\nTensor x Transposed:\n{x.mT}')

Tensor x:
tensor([[ 59, 102,  84],
        [ 78,   5,  41],
        [ 93,  63,  87],
        [ 50,  37,  10]])

Tensor x Transposed:
tensor([[ 59,  78,  93,  50],
        [102,   5,  63,  37],
        [ 84,  41,  87,  10]])


In [31]:
#Permute
pt = torch.arange(start=10,end=250,step=10).reshape(3,2,4)
pt.size()

torch.Size([3, 2, 4])

In [32]:
#Returns a view of the original tensor input with its dimensions permuted
# In other words, swapping the dimensions to a specific order stated in dims parameter.
pt.permute(dims=(1,2,0)).size()

torch.Size([2, 4, 3])

In [33]:
torch.where(y/2 < x, 1, 0)

tensor([[0, 1, 0],
        [1, 0, 0],
        [1, 1, 1],
        [0, 0, 0]])

In [34]:
print(y,'\n\n', y/2)

tensor([[155, 174, 181],
        [120, 150, 125],
        [166, 106, 150],
        [114, 168, 143]]) 

 tensor([[77.5000, 87.0000, 90.5000],
        [60.0000, 75.0000, 62.5000],
        [83.0000, 53.0000, 75.0000],
        [57.0000, 84.0000, 71.5000]])


Slice Notation

In [35]:
x

tensor([[ 59, 102,  84],
        [ 78,   5,  41],
        [ 93,  63,  87],
        [ 50,  37,  10]])

In [36]:
#Slice Notation
x[:,1]

tensor([102,   5,  63,  37])

In [37]:
x[:,1:2]

tensor([[102],
        [  5],
        [ 63],
        [ 37]])

In [38]:
x[:,1:2][1]

tensor([5])

Math Ops

In [39]:
x + y

tensor([[214, 276, 265],
        [198, 155, 166],
        [259, 169, 237],
        [164, 205, 153]])

In [40]:
x.sum()

tensor(709)

In [41]:
x * y

tensor([[ 9145, 17748, 15204],
        [ 9360,   750,  5125],
        [15438,  6678, 13050],
        [ 5700,  6216,  1430]])

In [42]:
torch.matmul( x, y.view(3,4))

tensor([[37045, 32592, 41723, 29904],
        [18990, 18871, 21836, 15753],
        [36915, 33975, 41907, 30279],
        [14800, 14465, 16872, 11352]])

In [43]:
print(f"""
{np.arange(1,4,1)}\n\n * \n\n{y.numpy()} \n\n= {(np.arange(1,4,1) * y.numpy())}



""")


[1 2 3]

 * 

[[155 174 181]
 [120 150 125]
 [166 106 150]
 [114 168 143]] 

= [[155 348 543]
 [120 300 375]
 [166 212 450]
 [114 336 429]]






In [44]:
print(f"""
{x[:,0:1].numpy()}\n\n * \n\n{np.arange(1,4,1)} \n\n= {(x[:,0:1].numpy() * np.arange(1,4,1))}



""")


[[59]
 [78]
 [93]
 [50]]

 * 

[1 2 3] 

= [[ 59 118 177]
 [ 78 156 234]
 [ 93 186 279]
 [ 50 100 150]]






## Tensor Attributes

    - Shape or Size (same thing)
    - Device (CPU or GPU)
    - Layout
    - Mean
    - Max
    - argmin, argmax
    - sum
    - unique

In [45]:
x.shape

torch.Size([4, 3])

In [46]:
x.size()

torch.Size([4, 3])

In [47]:
x.device

device(type='cpu')

In [48]:
x = x.type(torch.float64)
x.mean()

tensor(59.0833, dtype=torch.float64)

In [49]:
x.std()

tensor(31.6183, dtype=torch.float64)

In [50]:
print(f"""
Min Value: {x.min()}
Index of min value: {x.argmin()}
Max Value: {x.max()}
Index of max value: {x.argmax()}

Unique Values: {x.unique()}
""")


Min Value: 5.0
Index of min value: 4
Max Value: 102.0
Index of max value: 1

Unique Values: tensor([  5.,  10.,  37.,  41.,  50.,  59.,  63.,  78.,  84.,  87.,  93., 102.],
       dtype=torch.float64)



In [51]:
print(x,'\n\n',x.mean(dim=0, keepdim=True), '\n\n', '(75+12+4+86)/4 = ', (75+12+4+86)/4 )

tensor([[ 59., 102.,  84.],
        [ 78.,   5.,  41.],
        [ 93.,  63.,  87.],
        [ 50.,  37.,  10.]], dtype=torch.float64) 

 tensor([[70.0000, 51.7500, 55.5000]], dtype=torch.float64) 

 (75+12+4+86)/4 =  44.25


In [52]:
print(x,'\n\n',x.mean(dim=1, keepdim=True), '\n\n', '(75+51+100)/3 = ', format((75+51+100)/3,'1.4'))

tensor([[ 59., 102.,  84.],
        [ 78.,   5.,  41.],
        [ 93.,  63.,  87.],
        [ 50.,  37.,  10.]], dtype=torch.float64) 

 tensor([[81.6667],
        [41.3333],
        [81.0000],
        [32.3333]], dtype=torch.float64) 

 (75+51+100)/3 =  75.33


## Probability Distribution Functions

**Bernoulli**

In [53]:
# Toss a Coin 1 could represent heads and 0 tails

bernoulli = dist.Bernoulli(torch.tensor([0.5]))
# Tensor 0.5 represents the probability, which means 50% per event.


# Sample from the distribution
samples = []
for i in range(10):
    sample = bernoulli.sample() #Toss a Coin
    samples.append(sample)
    print(sample)
print(f"\nMean: {torch.mean(torch.stack(samples)):2.3f}") #Mean for all samples
print(f"Variance: {torch.var(torch.stack(samples)):2.3f}") #Variance for all samples

tensor([0.])
tensor([1.])
tensor([0.])
tensor([0.])
tensor([1.])
tensor([1.])
tensor([1.])
tensor([1.])
tensor([1.])
tensor([0.])

Mean: 0.600
Variance: 0.267


**Normal Distribution**

In [54]:
# for dist.Normal function need to input Mean and STD (0 and 1)
normal = dist.Normal(torch.tensor([0.0]), torch.tensor([1.0]))
normal_samples = []
for _ in range(10):
    ns = normal.sample()
    normal_samples.append(ns)
    print(ns)
    
print(f"\nMean: {torch.mean(torch.stack(normal_samples))}") #Mean for all samples
print(f"Variance: {torch.var(torch.stack(normal_samples))}") #Variance for all samples

tensor([1.2398])
tensor([0.3854])
tensor([-0.8882])
tensor([1.3042])
tensor([0.4053])
tensor([1.1156])
tensor([-1.0638])
tensor([-1.2994])
tensor([1.3309])
tensor([-2.0046])

Mean: 0.05251725763082504
Variance: 1.5740509033203125
